base_model_id: microsoft/Phi-3-mini-4k-instruct

adapter_path: /kaggle/input/datasets/hollychen12345/phi3-skill-lora-adapter/phi3_skill_lora_adapter

test_data_path: /kaggle/input/datasets/hollychen12345/test-xls/test.xls

output_path: outputs/prediction_samples.csv

sample_size: 10
random_seed: 42

batch_size: 2
max_input_length: 512
max_new_tokens: 12
